name: Contents Check

on: [push, pull_request]

jobs:
  test-contents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        #node-version: [12.x, 14.x]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: yarn
      - name: Contents Check
        run: yarn check-contents